---

- name: Include Variables
  include_vars: "{{ item }}"
  with_items:
    - group_vars/aws_vars

- name: Install python
  homebrew:
    name=python
    state=present

- name: Install pip
  easy_install:
    name=pip

- name: Install boto and aws-cli via pip
  become: yes
  pip:
    name={{ item }}
  with_items:
    - boto
    - awscli
