# vim:ft=ansible
- name: Upgrade All Packages to Latest
  become: yes
  apt:
     upgrade=dist
     update_cache=yes

- name: Set hostname
  become: yes
  hostname: name="{{ inventory_hostname }}"

- name: Install Default Packages
  become: yes
  apt:
    pkg={{ item }}
    state=present
  with_items:
    - "{{ system_packages.default }}"

- name: Remove useless packages from the cache
  become: yes
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes
