# vim:ft=ansible

- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Add NodeSource deb-src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main'
    state: present

- name: Install Node.js
  become: yes
  apt:
    pkg:
      - nodejs
    state: installed
    update_cache: yes

- name: Install PM2
  become: yes
  npm:
    name=pm2
    global=yes
