cap_deploy:
  user: cap
  sudo_perms: "/etc/init.d/nginx, /bin/mv, /bin/mkdir, /bin/ln, /usr/sbin/update-rc.d, /bin/chown"
  permissions:
    - { dir: '/srv/', entity: 'cap', etype: 'user', perms: 'rwx' }
