
nginx_custom_dirs:
    - { dir: 'auth', owner: 'root', group: 'root', mode: '0755' }

nginx_networks:
    allow:
      - "10.0.0.0/24"
      - "10.0.1.0/24"
      - "10.0.100.0/24"
      # - "204.210.139.149/32"
