---

- name: Configure Systems for Ansible and Terminal Use
  hosts: system-setup
  roles:
    - { role: system-setup, tags: ['system-setup'] }
    - { role: user-setup, tags: ['user-setup'] }
    - { role: acl-permissions, tags: ['acl'] }
  tags:
    - setup
    
- name: Configure AWS CLI
  hosts: aws-machines
  roles:
    - { role: aws-cli }
  tags:
    - aws-cli

- name: Configure NGINX Servers
  hosts: nginx-servers
  roles:
    - { role: nginx-server }
  tags:
    - nginx

- name: Configure Node.js Servers
  hosts: node-servers
  roles:
    - { role: node-server }
  tags:
    - node

# - name: Configure Servers for Capistrano Deploy
#   hosts: cap-deploy
#   roles:
#     - { role: capistrano-deploy }
#   tags:
#     - capistrano
